[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "advent"
path = "main.rs"

[dependencies]
axum = "0.7.9"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
