name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/nextjs-docker:latest

    # SSH into your VPS and deploy the new image
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd ~/advent
          
          # Pull the latest image from GitHub Container Registry
          echo "${{ secrets.VPS_PASSWORD }}" | sudo -S docker pull ghcr.io/${{ github.repository }}/nextjs-docker:latest
          
          # Stop and remove the old container
          echo "${{ secrets.VPS_PASSWORD }}" | sudo -S docker stop aocucats || true
          echo "${{ secrets.VPS_PASSWORD }}" | sudo -S docker rm aocucats || true
          
          # Run the new container with the same settings/environment variables
          echo "${{ secrets.VPS_PASSWORD }}" | sudo -S docker run -d --name aocucats --VIRTUAL_PORT 3333 --VIRTUAL_HOST aoc.cucats.org -p 3333:3333 \
            --env-file .env --network ssl_default \
            ghcr.io/${{ github.repository }}/nextjs-docker:latest
